openapi: 3.0.3
info:
  title: Fridge Master
  description: Fridge Master
  version: 1.0.0
servers:
  - url: 'http:\/\/localhost'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

paths:
  /locations:
    get:
      description: Returns a list of locations
      responses:
        '200':
          description: Successfully returned a list of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    blocks_available:
                      type: integer

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /calculate:
    post:
      description: Calculate booking info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - location_id
                - volume
                - temperature
                - start_date
                - end_date
              properties:
                location_id:
                  type: integer
                volume:
                  type: number
                temperature:
                  type: number
                start_date:
                  type: string
                end_date:
                  type: string

      responses:
        '200':
          description: Successfully returned calculated information
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    blocks_amount:
                      type: integer
                    price:
                      type: number
                    available:
                      type: boolean

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /bookings:
    post:
      description: Create booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - location_id
                - volume
                - temperature
                - start_date
                - end_date
                - calculated_blocks_amount
                - calculated_price
              properties:
                location_id:
                  type: integer
                volume:
                  type: number
                temperature:
                  type: number
                start_date:
                  type: string
                end_date:
                  type: string
                calculated_blocks_amount:
                  type: integer
                calculated_price:
                  type: number

      responses:
        '201':
          description: Successful create booking
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    get:
      description: Returns a list of user bookings
      responses:
        '200':
          description: Successfully returned a list of user bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    status:
                      type: string
                    price:
                      type: integer

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /bookings/{id}/code:
    get:
      description: Returns booking code by booking id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully returned booking code
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


